[book]
authors = ["FranCalveyra"]
language = "en"
multilingual = false
src = "src"
title = "Arquitectura de Nube en AWS"

[preprocessor.katex]
renderers = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
theme = "theme"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
